### ISSUE TITLE
Usable for implementing EQ Radio?

### ISSUE THREAD

**Issue by crawfordcomeaux** [Ttl/fmcw2#1]
I noticed you blogged about measuring breathing & heart rate. (http://hforsten.com/heartbeat-detection-with-radar.html)

 Do you think this design could be used to implement the system in this paper?
http://eqradio.csail.mit.edu/files/eqradio-paper.pdf

**Comment by Ttl** [comment]
Probably. I can send you the raw data of my own heartbeat measurements if you are interested in implementing the algorithm.
