### ISSUE TITLE
About processing with analysis.py

### ISSUE THREAD

**Issue by Ynafehts11** [Ttl/fmcw2#3]
Hi Henrik,
I'd like to ask you about the analysis.py code, it requires to read a filename.sync in line 49, is this file a copy of the previous file read in line 27 
(with changed name "filename.sync" or manual added extension ".sync")?

I tried to generate and verified data but had some trouble with this.
`File C:\analysis.py,  line 73, in  <module>
acc += syncs[i]
IndexError: list index out of range`

Thanks in advance!

**Comment by Ttl** [comment]
.sync file is generated by the fir program in "processing/fir" directory.
